workflows:
  ios-device-build:
    name: iOS Build with Signing + ExportOptions
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: "com.pims.pimsApp"
        TEAM_ID: "ABZGC66QRD"
        PROFILE_NAME: "profile"  # Name of uploaded .mobileprovision
        CERT_NAME: "Apple Development"  # Or Apple Distribution if using release

    scripts:
      - name: Generate iOS folder if missing
        script: |
          if [ ! -d "ios" ]; then
            flutter create .
          fi

      - name: Set iOS Deployment Target to 15.5
        script: |
          sed -i.bak "s/^# platform :ios.*/platform :ios, '15.5'/" ios/Podfile || echo "platform :ios, '15.5'" >> ios/Podfile

      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Build iOS archive
        script: |
          flutter build ios --release
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     archive \
                     CODE_SIGN_STYLE=Manual \
                     DEVELOPMENT_TEAM=$TEAM_ID \
                     PROVISIONING_PROFILE_SPECIFIER=$PROFILE_NAME \
                     PRODUCT_BUNDLE_IDENTIFIER=$APP_ID

      - name: Export IPA using ExportOptions.plist
        script: |
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
           "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string> <!-- Or 'ad-hoc' or 'app-store' -->
            <key>teamID</key>
            <string>$TEAM_ID</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$APP_ID</key>
              <string>$PROFILE_NAME</string>
            </dict>
            <key>compileBitcode</key>
            <false/>
            <key>signingCertificate</key>
            <string>$CERT_NAME</string>
            <key>signingStyle</key>
            <string>manual</string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
