workflows:
  ios-release:
    name: iOS Release with GUI Signing
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Set iOS deployment target
        script: |
          sed -i.bak "s/^# platform :ios.*/platform :ios, '15.5'/" ios/Podfile || echo "platform :ios, '15.5'" >> ios/Podfile

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS release
        script: flutter build ios --release

      - name: Archive for distribution
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     archive

      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     -exportPath build/ios/ipa \
                     -exportOptionsPlist ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
