workflows:
  ios-build:
    name: iOS Build (No Codesign)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Generate ios folder if missing
        script: |
          if [ ! -d "ios" ]; then
            flutter create .
          fi
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Force iOS Deployment Target to 13.0
        script: |
          echo "Setting iOS platform to 13.0 manually..."
          awk '{sub(/platform :ios, .*/, "platform :ios, '\''13.0'\''")} 1' ios/Podfile > ios/Podfile.new
          mv ios/Podfile.new ios/Podfile
          cat ios/Podfile
      - name: Build iOS (Unsigned)
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
