workflows:
  ios-build:
    name: iOS Build (Runner.app only)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Generate ios folder if missing
        script: |
          if [ ! -d "ios" ]; then
            flutter create .
          fi

      - name: Set iOS Deployment Target to 15.5
        script: |
          sed -i.bak "s/^# platform :ios.*/platform :ios, '15.5'/" ios/Podfile || echo "platform :ios, '15.5'" >> ios/Podfile

      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign

      - name: Patch xcconfig for CocoaPods (Base Config fix)
        script: |
          cd ios
          sed -i '' 's|//.*base.*|base_configuration = "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig";|' Runner.xcodeproj/project.pbxproj
          cd ..

      - name: Archive iOS app with xcodebuild
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     archive \
                     CODE_SIGNING_ALLOWED=NO \
                     -allowProvisioningUpdates \
                     -quiet

    artifacts:
      - build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app
