workflows:
  ios-build:
    name: iOS Build (No Codesign)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Generate ios folder if missing
        script: |
          if [ ! -d "ios" ]; then
            flutter create .
          fi
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Set iOS Deployment Target to 15.5
        script: |
          echo "Setting iOS deployment target to 15.5"
          sed -i.bak "s/^# platform :ios.*/platform :ios, '15.5'/" ios/Podfile || echo "platform :ios, '15.5'" >> ios/Podfile
          cat ios/Podfile
      - name: Build iOS .ipa (No Codesign)
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
