name: pims_app
description: "A Flutter application for Prasad Institute of Medical Sciences Lucknow."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  uuid: ^4.3.3
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  url_launcher: ^6.2.1
  http: ^1.1.0
  webview_flutter: ^4.10.0
  google_sign_in: ^6.2.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  
  
  assets:
    - assets/images/
    - assets/

  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Light.ttf
  #         weight: 300

