// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEB-v8n8FwUoiC618YpZfZFOpmdOhL1tY',
    appId: '1:250221986887:web:3cfdb11ddee801000b9d62',
    messagingSenderId: '250221986887',
    projectId: 'pimsfinal-f2bf6',
    authDomain: 'pimsfinal-f2bf6.firebaseapp.com',
    storageBucket: 'pimsfinal-f2bf6.firebasestorage.app',
    measurementId: 'G-MB66MP05LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6_M_KQOFFEoJ-urBBZug3JW8ZlixHPXc',
    appId: '1:250221986887:android:c30ed0e0a5a648930b9d62',
    messagingSenderId: '250221986887',
    projectId: 'pimsfinal-f2bf6',
    storageBucket: 'pimsfinal-f2bf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm0jiCXCvSTmQNZHMbhNrhoQjANd6fDfE',
    appId: '1:250221986887:ios:88e56e62da4ee5490b9d62',
    messagingSenderId: '250221986887',
    projectId: 'pimsfinal-f2bf6',
    storageBucket: 'pimsfinal-f2bf6.firebasestorage.app',
    androidClientId: '250221986887-4a9gucoev6fqt1ns184qfbon1k9p3ou0.apps.googleusercontent.com',
    iosClientId: '250221986887-8j7j1tjj4q8bg4kuf0qj1mpvggo3p4i6.apps.googleusercontent.com',
    iosBundleId: 'com.pims.pimsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm0jiCXCvSTmQNZHMbhNrhoQjANd6fDfE',
    appId: '1:250221986887:ios:3240c3c3579e08270b9d62',
    messagingSenderId: '250221986887',
    projectId: 'pimsfinal-f2bf6',
    storageBucket: 'pimsfinal-f2bf6.firebasestorage.app',
    androidClientId: '250221986887-4a9gucoev6fqt1ns184qfbon1k9p3ou0.apps.googleusercontent.com',
    iosClientId: '250221986887-vf7qrla7qkisgpng7r4ithdjt368f15j.apps.googleusercontent.com',
    iosBundleId: 'com.example.pimsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEB-v8n8FwUoiC618YpZfZFOpmdOhL1tY',
    appId: '1:250221986887:web:e9770462bf3f5b450b9d62',
    messagingSenderId: '250221986887',
    projectId: 'pimsfinal-f2bf6',
    authDomain: 'pimsfinal-f2bf6.firebaseapp.com',
    storageBucket: 'pimsfinal-f2bf6.firebasestorage.app',
    measurementId: 'G-S97NGLHKPZ',
  );

}